<?xml version="1.0" encoding="UTF-8"?>
<!-- 
History of Changes:
Vers.    Date              Author             Comment
====    =========  ===========  ===================================================
1.0		28.08.2013	Reto Renner		Initial version of wsdl
1.1		2013-09-06	Marco Abraham	delete OPM service
-->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soapjms="http://www.w3.org/2008/07/soap/bindings/JMS/" xmlns:wsdlbase="http://www.vodafone.de/ESB/Service/Base/BaseAbstract-001.wsdl" xmlns:bks="http://www.vodafone.de/ESB/Service/SBUS/BKS/BKS-WBCI-001" xmlns:tns="http://www.vodafone.de/ESB/Service/SBUS/BKS-WBCI-001.wsdl" xmlns:ns="http://www.vodafone.de/ESB/Schema/Common/BaseTypes-ESB-001" targetNamespace="http://www.vodafone.de/ESB/Service/SBUS/BKS-WBCI-001.wsdl">
	<wsdl:import namespace="http://www.vodafone.de/ESB/Service/Base/BaseAbstract-001.wsdl" location="../../Base/BaseAbstract-001.wsdl"/>
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="http://www.vodafone.de/ESB/Service/SBUS/BKS/BKS-WBCI-001" schemaLocation="BKS-WBCI-001.xsd"/>
		</schema>
	</wsdl:types>	
	<wsdl:message name="WbciGetDtagContractNumberRequest">
		<wsdl:part name="WbciGetDtagContractNumberRequest" element="bks:WbciGetDtagContractNumberRequest"/>
	</wsdl:message>
	<wsdl:message name="WbciGetDtagContractNumberResponse">
		<wsdl:part name="WbciGetDtagContractNumberResponse" element="bks:WbciGetDtagContractNumberResponse"/>
	</wsdl:message>
	<wsdl:portType name="BKSPortType">		
		<wsdl:operation name="WbciGetDtagContractNumber">
			<wsdl:input name="WbciGetDtagContractNumberRequest" message="tns:WbciGetDtagContractNumberRequest"/>
			<wsdl:output name="WbciGetDtagContractNumberResponse" message="tns:WbciGetDtagContractNumberResponse"/>
			<wsdl:fault name="functionalESBException" message="wsdlbase:functionalESBException"/>
			<wsdl:fault name="technicalESBException" message="wsdlbase:technicalESBException"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="BKSJMSBinding" type="tns:BKSPortType">
		<wsoap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<!--<wsoap12:binding style="document" transport="http://www.w3.org/2008/07/soap/bindings/JMS/"/>-->		
		<wsdl:operation name="WbciGetDtagContractNumber">
			<wsoap12:operation soapAction="/BKS-001/WbciGetDtagContractNumber" soapActionRequired="true" style="document"/>
			<soapjms:targetService>BKS</soapjms:targetService>
			<wsdl:input>
				<wsoap12:body parts="WbciGetDtagContractNumberRequest" use="literal"/>
				<wsoap12:header message="wsdlbase:appMonDetailsHeader" part="AppMonDetails" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<wsoap12:body parts="WbciGetDtagContractNumberResponse" use="literal"/>
				<wsoap12:header message="wsdlbase:appMonDetailsHeader" part="AppMonDetails" use="literal"/>
			</wsdl:output>
			<wsdl:fault name="functionalESBException">
				<wsoap12:fault name="functionalESBException" use="literal"/>
			</wsdl:fault>
			<wsdl:fault name="technicalESBException">
				<wsoap12:fault name="technicalESBException" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="BKSService">
		<wsdl:port name="BKSServiceJMSEndpoint" binding="tns:BKSJMSBinding">
			<wsoap12:address location="jms:queue:endpointQeue"/>
			<!-- optional: replaces "wsoap12:address": -->
			<!--
            <jms:address
                destinationStyle="queue"
                jndiDestinationName="endpointQeue"
                jndiConnectionFactoryName="jmsFactory">
            </jms:address>
            -->
		</wsdl:port>
	</wsdl:service>
	<!-- xmlns:jms="http://cxf.apache.org/transports/jms" -->
</wsdl:definitions>
